name: Python application

on:
  push:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Run Tests
      run: |
        python -m unittest test_plugin.py

  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: write
    needs: [build]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"
      - name: Pack Plugin
        working-directory: dev
        run: |
          python calibre_plugin_packer.py
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          draft: false
          make_latest: true
          files: |
            ./out/*.zip
